MODEL=digital-watch

tcmc:
	$(MAKE) -f ../../Makefile-dash.mk  MODEL=$(MODEL) METHOD=tcmc

traces:
	$(MAKE) -f ../../Makefile-dash.mk  MODEL=$(MODEL) METHOD=traces

clean:
	$(MAKE) -f ../../Makefile-dash.mk clean
